// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Game struct {
	ID            string          `json:"id"`
	Week          int             `json:"week"`
	Date          string          `json:"date"`
	OpponentID    string          `json:"opponentId"`
	OpponentName  string          `json:"opponentName"`
	Location      GameLocation    `json:"location"`
	Result        GameResult      `json:"result"`
	TeamScore     *int            `json:"teamScore,omitempty"`
	OpponentScore *int            `json:"opponentScore,omitempty"`
	Playoff       bool            `json:"playoff"`
	Notes         *string         `json:"notes,omitempty"`
	Prediction    *GamePrediction `json:"prediction,omitempty"`
}

type GamePrediction struct {
	WinProbability  float64    `json:"winProbability"`
	PredictedResult GameResult `json:"predictedResult"`
	// The margin that the model expects for this team, in points, with the home edge included. A
	// negative margin is an expected loss.
	PredictedMargin float64 `json:"predictedMargin"`
	TeamRating      float64 `json:"teamRating"`
	OpponentRating  float64 `json:"opponentRating"`
	// The date of the prediction. It is the date of the game for a game played before the last
	// update, and the date of the last update for a game not yet played.
	AsOf string `json:"asOf"`
}

type Query struct {
}

type Record struct {
	Wins   int `json:"wins"`
	Losses int `json:"losses"`
	Ties   int `json:"ties"`
}

type Team struct {
	ID             string        `json:"id"`
	Season         int           `json:"season"`
	Name           string        `json:"name"`
	Mascot         *string       `json:"mascot,omitempty"`
	City           *string       `json:"city,omitempty"`
	Division       *int          `json:"division,omitempty"`
	Region         *int          `json:"region,omitempty"`
	PrimaryColor   *string       `json:"primaryColor,omitempty"`
	SecondaryColor *string       `json:"secondaryColor,omitempty"`
	Record         *Record       `json:"record"`
	Rating         *TeamRating   `json:"rating,omitempty"`
	RatingHistory  []*TeamRating `json:"ratingHistory"`
	Schedule       []*Game       `json:"schedule"`
}

// The margin rating of a team on one date. A rating is a number of points. The gap between two
// ratings of the same date is the margin that the model expects on a neutral field.
type TeamRating struct {
	Season int `json:"season"`
	// The rating in points. The value 0 has no meaning of its own, so compare two ratings of one date.
	Rating float64 `json:"rating"`
	// The rating minus the median rating of the Ohio teams on the same date, so that 0 is the median
	// team.
	RelativeRating float64 `json:"relativeRating"`
	Rank           int     `json:"rank"`
	// The rank of the team in the snapshot before this one in the same season. It is null when the
	// season has no earlier snapshot, or when the team is not in that snapshot.
	PreviousRank *int   `json:"previousRank,omitempty"`
	AsOf         string `json:"asOf"`
}

type GameLocation string

const (
	GameLocationHome    GameLocation = "HOME"
	GameLocationAway    GameLocation = "AWAY"
	GameLocationNeutral GameLocation = "NEUTRAL"
)

var AllGameLocation = []GameLocation{
	GameLocationHome,
	GameLocationAway,
	GameLocationNeutral,
}

func (e GameLocation) IsValid() bool {
	switch e {
	case GameLocationHome, GameLocationAway, GameLocationNeutral:
		return true
	}
	return false
}

func (e GameLocation) String() string {
	return string(e)
}

func (e *GameLocation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameLocation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameLocation", str)
	}
	return nil
}

func (e GameLocation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type GameResult string

const (
	GameResultWin      GameResult = "WIN"
	GameResultLoss     GameResult = "LOSS"
	GameResultTie      GameResult = "TIE"
	GameResultCanceled GameResult = "CANCELED"
	GameResultUnknown  GameResult = "UNKNOWN"
)

var AllGameResult = []GameResult{
	GameResultWin,
	GameResultLoss,
	GameResultTie,
	GameResultCanceled,
	GameResultUnknown,
}

func (e GameResult) IsValid() bool {
	switch e {
	case GameResultWin, GameResultLoss, GameResultTie, GameResultCanceled, GameResultUnknown:
		return true
	}
	return false
}

func (e GameResult) String() string {
	return string(e)
}

func (e *GameResult) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameResult(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameResult", str)
	}
	return nil
}

func (e GameResult) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TeamSort string

const (
	TeamSortRating TeamSort = "RATING"
	TeamSortName   TeamSort = "NAME"
)

var AllTeamSort = []TeamSort{
	TeamSortRating,
	TeamSortName,
}

func (e TeamSort) IsValid() bool {
	switch e {
	case TeamSortRating, TeamSortName:
		return true
	}
	return false
}

func (e TeamSort) String() string {
	return string(e)
}

func (e *TeamSort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TeamSort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TeamSort", str)
	}
	return nil
}

func (e TeamSort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
