// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Game struct {
	ID            string          `json:"id"`
	Week          int             `json:"week"`
	Date          string          `json:"date"`
	OpponentID    string          `json:"opponentId"`
	OpponentName  string          `json:"opponentName"`
	Location      GameLocation    `json:"location"`
	Result        GameResult      `json:"result"`
	TeamScore     *int            `json:"teamScore,omitempty"`
	OpponentScore *int            `json:"opponentScore,omitempty"`
	Playoff       bool            `json:"playoff"`
	Notes         *string         `json:"notes,omitempty"`
	Prediction    *GamePrediction `json:"prediction,omitempty"`
}

type GamePrediction struct {
	WinProbability  float64    `json:"winProbability"`
	PredictedResult GameResult `json:"predictedResult"`
	// The margin that the model expects for this team, in points, with the home edge included. A
	// negative margin is an expected loss.
	PredictedMargin float64 `json:"predictedMargin"`
	TeamRating      float64 `json:"teamRating"`
	OpponentRating  float64 `json:"opponentRating"`
	// The date of the prediction. It is the date of the game for a game played before the last
	// update, and the date of the last update for a game not yet played.
	AsOf string `json:"asOf"`
}

type Query struct {
}

type Record struct {
	Wins   int `json:"wins"`
	Losses int `json:"losses"`
	Ties   int `json:"ties"`
}

type Team struct {
	// The key of the team in one season. A team has a different id in each season.
	ID     string `json:"id"`
	Season int    `json:"season"`
	// The identifier of the team in its source. For a team from joeeitel.com, it is the number that
	// joeeitel.com gives to the team. It stays the same from one season to the next.
	SourceID string  `json:"sourceId"`
	Name     string  `json:"name"`
	Mascot   *string `json:"mascot,omitempty"`
	City     *string `json:"city,omitempty"`
	// The Ohio county of the school, as joeeitel.com gives it, such as Stark. It has no word "County".
	// It is null when the source does not state it.
	County         *string `json:"county,omitempty"`
	Division       *int    `json:"division,omitempty"`
	Region         *int    `json:"region,omitempty"`
	PrimaryColor   *string `json:"primaryColor,omitempty"`
	SecondaryColor *string `json:"secondaryColor,omitempty"`
	Record         *Record `json:"record"`
	// The number of games this season that the team played against a team that is not recorded as an
	// Ohio team. The rating leaves these games out, so a team with many of them has fewer games behind
	// its rating. A game counts only when it has a result and both scores. A canceled game and a
	// forfeit do not count. The number has a meaning only for an Ohio team, because the rating leaves
	// out every game of a team from another state.
	OutOfStateGamesPlayed int           `json:"outOfStateGamesPlayed"`
	Rating                *TeamRating   `json:"rating,omitempty"`
	RatingHistory         []*TeamRating `json:"ratingHistory"`
	Schedule              []*Game       `json:"schedule"`
}

// The margin rating of a team on one date. A rating is a number of points. The gap between two
// ratings of the same date is the margin that the model expects on a neutral field.
type TeamRating struct {
	Season int `json:"season"`
	// The rating in points. The value 0 has no meaning of its own, so compare two ratings of one date.
	Rating float64 `json:"rating"`
	// The rating minus the median rating of the Ohio teams on the same date, so that 0 is the median
	// team.
	RelativeRating float64 `json:"relativeRating"`
	Rank           int     `json:"rank"`
	// The rank of the team one week before asOf, among the teams of the same snapshot. A rating changes
	// only when a team plays, and the rating service keeps the ratings that both teams carried into
	// each played game. So the API reads the rating of each team on that day from the games of the
	// week, and it needs no earlier snapshot. A team with no game in that week keeps its rating. A
	// snapshot with no game in the week before it, such as one of 31 December, has the same rank here
	// as in rank.
	PreviousRank *int   `json:"previousRank,omitempty"`
	AsOf         string `json:"asOf"`
}

type GameLocation string

const (
	GameLocationHome    GameLocation = "HOME"
	GameLocationAway    GameLocation = "AWAY"
	GameLocationNeutral GameLocation = "NEUTRAL"
)

var AllGameLocation = []GameLocation{
	GameLocationHome,
	GameLocationAway,
	GameLocationNeutral,
}

func (e GameLocation) IsValid() bool {
	switch e {
	case GameLocationHome, GameLocationAway, GameLocationNeutral:
		return true
	}
	return false
}

func (e GameLocation) String() string {
	return string(e)
}

func (e *GameLocation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameLocation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameLocation", str)
	}
	return nil
}

func (e GameLocation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type GameResult string

const (
	GameResultWin      GameResult = "WIN"
	GameResultLoss     GameResult = "LOSS"
	GameResultTie      GameResult = "TIE"
	GameResultCanceled GameResult = "CANCELED"
	GameResultUnknown  GameResult = "UNKNOWN"
)

var AllGameResult = []GameResult{
	GameResultWin,
	GameResultLoss,
	GameResultTie,
	GameResultCanceled,
	GameResultUnknown,
}

func (e GameResult) IsValid() bool {
	switch e {
	case GameResultWin, GameResultLoss, GameResultTie, GameResultCanceled, GameResultUnknown:
		return true
	}
	return false
}

func (e GameResult) String() string {
	return string(e)
}

func (e *GameResult) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameResult(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameResult", str)
	}
	return nil
}

func (e GameResult) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TeamSort string

const (
	TeamSortRating TeamSort = "RATING"
	TeamSortName   TeamSort = "NAME"
)

var AllTeamSort = []TeamSort{
	TeamSortRating,
	TeamSortName,
}

func (e TeamSort) IsValid() bool {
	switch e {
	case TeamSortRating, TeamSortName:
		return true
	}
	return false
}

func (e TeamSort) String() string {
	return string(e)
}

func (e *TeamSort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TeamSort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TeamSort", str)
	}
	return nil
}

func (e TeamSort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
