name: ohfootball
version: "1.0.0"
config-version: 2

profile: ohfootball

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

clean-targets:
  - target
  - dbt_packages

models:
  ohfootball:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
      +schema: ohfootball_int
    marts:
      +materialized: table
      +schema: ohfootball_marts

seeds:
  ohfootball:
    +schema: ohfootball_seeds
    school_locations:
      +column_types:
        team_id: text
        team_name: text
        latitude: double precision
        longitude: double precision
