// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertGames implements pgx.CopyFromSource.
type iteratorForInsertGames struct {
	rows                 []InsertGamesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertGames) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertGames) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ScrapeRunID,
		r.rows[0].Season,
		r.rows[0].SourceTeamID,
		r.rows[0].GameDate,
		r.rows[0].HomeAway,
		r.rows[0].OpponentTeamID,
		r.rows[0].Result,
		r.rows[0].Score,
		r.rows[0].Notes,
		r.rows[0].Playoff,
	}, nil
}

func (r iteratorForInsertGames) Err() error {
	return nil
}

func (q *Queries) InsertGames(ctx context.Context, arg []InsertGamesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"ohfootball_raw", "games"}, []string{"scrape_run_id", "season", "source_team_id", "game_date", "home_away", "opponent_team_id", "result", "score", "notes", "playoff"}, &iteratorForInsertGames{rows: arg})
}
