// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppendGamesParams struct {
	ScrapeRunID    pgtype.UUID
	Season         int32
	SourceTeamID   pgtype.Text
	GameDate       pgtype.Text
	HomeAway       pgtype.Text
	OpponentTeamID pgtype.Text
	Result         pgtype.Text
	Score          pgtype.Text
	Notes          pgtype.Text
	Playoff        pgtype.Text
}

type AppendTeamsParams struct {
	ScrapeRunID    pgtype.UUID
	Season         int32
	TeamID         string
	Name           pgtype.Text
	Mascot         pgtype.Text
	City           pgtype.Text
	State          pgtype.Text
	County         pgtype.Text
	PrimaryColor   pgtype.Text
	SecondaryColor pgtype.Text
	Division       pgtype.Text
	Region         pgtype.Text
}

const finishScrapeRun = `-- name: FinishScrapeRun :exec
UPDATE ohfootball_metadata.scrape_runs
SET finished_at = NOW(),
    status = $2,
    error_message = $3
WHERE id = $1
`

type FinishScrapeRunParams struct {
	ID           pgtype.UUID
	Status       string
	ErrorMessage pgtype.Text
}

func (q *Queries) FinishScrapeRun(ctx context.Context, arg FinishScrapeRunParams) error {
	_, err := q.db.Exec(ctx, finishScrapeRun, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}

const startScrapeRun = `-- name: StartScrapeRun :one
INSERT INTO ohfootball_metadata.scrape_runs (
    scraper_version,
    root_url,
    status
) VALUES (
    $1,
    $2,
    'running'
)
RETURNING id
`

type StartScrapeRunParams struct {
	ScraperVersion string
	RootUrl        string
}

func (q *Queries) StartScrapeRun(ctx context.Context, arg StartScrapeRunParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, startScrapeRun, arg.ScraperVersion, arg.RootUrl)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
