// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishScrapeRun = `-- name: FinishScrapeRun :exec
UPDATE ohfootball_metadata.scrape_runs
SET finished_at = NOW(),
    status = $2,
    error_message = $3
WHERE id = $1
`

type FinishScrapeRunParams struct {
	ID           pgtype.UUID
	Status       string
	ErrorMessage pgtype.Text
}

func (q *Queries) FinishScrapeRun(ctx context.Context, arg FinishScrapeRunParams) error {
	_, err := q.db.Exec(ctx, finishScrapeRun, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}

type InsertGamesParams struct {
	ScrapeRunID    pgtype.UUID
	Season         int32
	SourceTeamID   pgtype.Text
	GameDate       pgtype.Text
	HomeAway       pgtype.Text
	OpponentTeamID pgtype.Text
	Result         pgtype.Text
	Score          pgtype.Text
	Notes          pgtype.Text
	Playoff        pgtype.Text
}

type InsertOhhsfbdbGamesParams struct {
	ScrapeRunID        pgtype.UUID
	Sheet              string
	Season             int32
	Week               pgtype.Text
	GameDate           pgtype.Text
	DayOfWeek          pgtype.Text
	HomeAway           pgtype.Text
	OpponentName       pgtype.Text
	OpponentSheet      pgtype.Text
	TeamScore          pgtype.Text
	OpponentScore      pgtype.Text
	Overtime           pgtype.Text
	Result             pgtype.Text
	OpponentConference pgtype.Text
	OpponentDivision   pgtype.Text
	OpponentRegion     pgtype.Text
	PlayoffRound       pgtype.Text
	TeamSeed           pgtype.Text
	OpponentSeed       pgtype.Text
	Stadium            pgtype.Text
	Location           pgtype.Text
}

type InsertOhhsfbdbIndexEntriesParams struct {
	ScrapeRunID pgtype.UUID
	Position    int32
	SchoolName  string
	Sheet       string
}

type InsertOhhsfbdbSeasonSummariesParams struct {
	ScrapeRunID      pgtype.UUID
	Sheet            string
	Season           int32
	Conference       pgtype.Text
	RegularWins      pgtype.Text
	RegularLosses    pgtype.Text
	RegularTies      pgtype.Text
	ConferenceWins   pgtype.Text
	ConferenceLosses pgtype.Text
	ConferenceTies   pgtype.Text
	PlayoffWins      pgtype.Text
	PlayoffLosses    pgtype.Text
	Division         pgtype.Text
	Region           pgtype.Text
	Rank             pgtype.Text
}

const insertOhhsfbdbTeam = `-- name: InsertOhhsfbdbTeam :exec
INSERT INTO ohfootball_raw.ohhsfbdb_teams (
    scrape_run_id,
    sheet,
    team_number,
    short_name
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type InsertOhhsfbdbTeamParams struct {
	ScrapeRunID pgtype.UUID
	Sheet       string
	TeamNumber  pgtype.Text
	ShortName   pgtype.Text
}

func (q *Queries) InsertOhhsfbdbTeam(ctx context.Context, arg InsertOhhsfbdbTeamParams) error {
	_, err := q.db.Exec(ctx, insertOhhsfbdbTeam,
		arg.ScrapeRunID,
		arg.Sheet,
		arg.TeamNumber,
		arg.ShortName,
	)
	return err
}

const insertTeam = `-- name: InsertTeam :exec
INSERT INTO ohfootball_raw.teams (
    scrape_run_id,
    season,
    team_id,
    name,
    mascot,
    city,
    state,
    county,
    primary_color,
    secondary_color,
    division,
    region
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
`

type InsertTeamParams struct {
	ScrapeRunID    pgtype.UUID
	Season         int32
	TeamID         string
	Name           pgtype.Text
	Mascot         pgtype.Text
	City           pgtype.Text
	State          pgtype.Text
	County         pgtype.Text
	PrimaryColor   pgtype.Text
	SecondaryColor pgtype.Text
	Division       pgtype.Text
	Region         pgtype.Text
}

func (q *Queries) InsertTeam(ctx context.Context, arg InsertTeamParams) error {
	_, err := q.db.Exec(ctx, insertTeam,
		arg.ScrapeRunID,
		arg.Season,
		arg.TeamID,
		arg.Name,
		arg.Mascot,
		arg.City,
		arg.State,
		arg.County,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.Division,
		arg.Region,
	)
	return err
}

const startScrapeRun = `-- name: StartScrapeRun :one
INSERT INTO ohfootball_metadata.scrape_runs (
    scraper_version,
    root_url,
    status
) VALUES (
    $1,
    $2,
    'running'
)
RETURNING id
`

type StartScrapeRunParams struct {
	ScraperVersion string
	RootUrl        string
}

func (q *Queries) StartScrapeRun(ctx context.Context, arg StartScrapeRunParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, startScrapeRun, arg.ScraperVersion, arg.RootUrl)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
