// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppendGamesParams struct {
	ScrapeRunID    pgtype.UUID
	Season         int32
	SourceTeamID   pgtype.Text
	GameDate       pgtype.Text
	HomeAway       pgtype.Text
	OpponentTeamID pgtype.Text
	Result         pgtype.Text
	Score          pgtype.Text
	Notes          pgtype.Text
	Playoff        pgtype.Text
}

type AppendTeamsParams struct {
	ScrapeRunID    pgtype.UUID
	Season         int32
	TeamID         string
	Name           pgtype.Text
	Mascot         pgtype.Text
	City           pgtype.Text
	State          pgtype.Text
	County         pgtype.Text
	PrimaryColor   pgtype.Text
	SecondaryColor pgtype.Text
	Division       pgtype.Text
	Region         pgtype.Text
}

const finishScrapeRun = `-- name: FinishScrapeRun :exec
UPDATE ohfootball_metadata.scrape_runs
SET finished_at = NOW(),
    status = $2,
    error_message = $3
WHERE id = $1
`

type FinishScrapeRunParams struct {
	ID           pgtype.UUID
	Status       string
	ErrorMessage pgtype.Text
}

func (q *Queries) FinishScrapeRun(ctx context.Context, arg FinishScrapeRunParams) error {
	_, err := q.db.Exec(ctx, finishScrapeRun, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}

const insertTeam = `-- name: InsertTeam :exec
INSERT INTO ohfootball_raw.teams (
    scrape_run_id,
    season,
    team_id,
    name,
    mascot,
    city,
    state,
    county,
    primary_color,
    secondary_color,
    division,
    region
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
`

type InsertTeamParams struct {
	ScrapeRunID    pgtype.UUID
	Season         int32
	TeamID         string
	Name           pgtype.Text
	Mascot         pgtype.Text
	City           pgtype.Text
	State          pgtype.Text
	County         pgtype.Text
	PrimaryColor   pgtype.Text
	SecondaryColor pgtype.Text
	Division       pgtype.Text
	Region         pgtype.Text
}

func (q *Queries) InsertTeam(ctx context.Context, arg InsertTeamParams) error {
	_, err := q.db.Exec(ctx, insertTeam,
		arg.ScrapeRunID,
		arg.Season,
		arg.TeamID,
		arg.Name,
		arg.Mascot,
		arg.City,
		arg.State,
		arg.County,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.Division,
		arg.Region,
	)
	return err
}

const listSuccessfulSeasons = `-- name: ListSuccessfulSeasons :many
SELECT DISTINCT teams.season
FROM ohfootball_raw.teams AS teams
INNER JOIN ohfootball_metadata.scrape_runs AS runs
    ON runs.id = teams.scrape_run_id
WHERE runs.status = 'succeeded'
  AND teams.season BETWEEN $1 AND $2
ORDER BY teams.season
`

type ListSuccessfulSeasonsParams struct {
	StartSeason int32
	EndSeason   int32
}

func (q *Queries) ListSuccessfulSeasons(ctx context.Context, arg ListSuccessfulSeasonsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, listSuccessfulSeasons, arg.StartSeason, arg.EndSeason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var season int32
		if err := rows.Scan(&season); err != nil {
			return nil, err
		}
		items = append(items, season)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startScrapeRun = `-- name: StartScrapeRun :one
INSERT INTO ohfootball_metadata.scrape_runs (
    scraper_version,
    root_url,
    status
) VALUES (
    $1,
    $2,
    'running'
)
RETURNING id
`

type StartScrapeRunParams struct {
	ScraperVersion string
	RootUrl        string
}

func (q *Queries) StartScrapeRun(ctx context.Context, arg StartScrapeRunParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, startScrapeRun, arg.ScraperVersion, arg.RootUrl)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
