package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/StephenODea54/services/api/graph/model"
)

// CurrentSeason is the resolver for the currentSeason field.
func (r *queryResolver) CurrentSeason(ctx context.Context) (int, error) {
	return r.Store.CurrentSeason(ctx)
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context, season *int, search *string, region *int, division *int, sort *model.TeamSort, limit *int) ([]*model.Team, error) {
	return r.Store.ListTeams(ctx, season, search, region, division, sort, limit)
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, id string) (*model.Team, error) {
	return r.Store.Team(ctx, id)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
