package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/StephenODea54/services/api/graph/model"
)

// CurrentSeason is the resolver for the currentSeason field.
func (r *queryResolver) CurrentSeason(ctx context.Context) (int, error) {
	return r.Store.CurrentSeason(ctx)
}

// Seasons is the resolver for the seasons field.
func (r *queryResolver) Seasons(ctx context.Context) ([]int, error) {
	return r.Store.Seasons(ctx)
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context, season *int, search *string, region *int, division *int, sort *model.TeamSort, limit *int) ([]*model.Team, error) {
	return r.Store.ListTeams(ctx, season, search, region, division, sort, limit)
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, id string, season *int) (*model.Team, error) {
	return r.Store.Team(ctx, id, season)
}

// ModelAccuracy is the resolver for the modelAccuracy field.
func (r *queryResolver) ModelAccuracy(ctx context.Context, fromSeason *int, toSeason *int) (*model.ModelAccuracy, error) {
	return r.Store.ModelAccuracy(ctx, fromSeason, toSeason)
}

// Program is the resolver for the program field.
func (r *queryResolver) Program(ctx context.Context, sourceID string) (*model.Program, error) {
	return r.Store.Program(ctx, sourceID)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
